### ISSUE TITLE
ModuleNotFoundError: No module named 'models.test_model'

### ISSUE THREAD

**Issue by 1098183715** [mingyuyng/Deep-JSCC-for-images-with-OFDM#4]
I used train.py and I got the result. but, In test.py，why  exist a mistake that ModuleNotFoundError: No module named 'models.test_model'.how to solve it ?
`Files already downloaded and verified
#training images = 10000
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/content/drive/My Drive/Deep-JSCC/models/__init__.py", line 64, in create_model
    model = find_model_using_name(opt.model)
  File "/content/drive/My Drive/Deep-JSCC/models/__init__.py", line 33, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.test_model'`

**Comment by ManXu1** [comment]
> 

Have you solved it?

**Comment by jasmine202106** [comment]
i also met this problem.

**Comment by WenBingo** [comment]
想请教一下，在channel.py -> Channel.forward 中
 output_real = batch_conv1d(signal_real, cof_real) - batch_conv1d(signal_imag, cof_imag)   # (NxP)x(L+SMK-1)
 output_imag = batch_conv1d(signal_real, cof_imag) + batch_conv1d(signal_imag, cof_real)   # (NxP)x(L+SMK-1)
 这两句的作用是什么，没有太理解

**Comment by ccu1tn** [comment]
@1098183715 Hello. 
I used train.py and I did not get the result. Please help me

My steps use the following: 
1. start visdoms by localhost. This result likes 
![image](https://github.com/mingyuyng/Deep-JSCC-for-images-with-OFDM/assets/43333942/635e2a53-b7c0-4e6c-9166-a3e4c806bb32) 
2. Can not run anything like this 
![image](https://github.com/mingyuyng/Deep-JSCC-for-images-with-OFDM/assets/43333942/c5e32999-ebcc-42a1-9013-cd9ee530c81b)

My environment is: 
Python 3.8.18
numpy=1.24.3
pytorch=2.0.1+cu117
cuda=12.2
dominate=2.8.0
scipy=1.10.1
visdom=0.2.4
I use vs code to run.

**Comment by ccu1tn** [comment]
@1098183715 Have you solved it? 
I also met a problem like yours. 
![image](https://github.com/mingyuyng/Deep-JSCC-for-images-with-OFDM/assets/43333942/cf5222bf-04b7-4717-b63b-4b40fcd53342)
Also, why are PARA values always 0.00 ?
![image](https://github.com/mingyuyng/Deep-JSCC-for-images-with-OFDM/assets/43333942/4f117a68-3bf1-40de-bfc0-7779bc9fdcdb)

Please give me some of your ideas... 
thanks

**Comment by dmwlx** [comment]
请问这个问题解决了吗

**Comment by ccu1tn** [comment]
@dmwlx not yet

**Comment by bigmc030318** [comment]
怎么解决，求大佬帮一下
